name: Build & Release lifecycle-hook-job

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "services/lifecycle-hook-job/**"
      - ".github/workflows/ryvn-lifecycle-hook-job-release.yaml"
  pull_request:
    paths:
      - "services/lifecycle-hook-job/**"
      - ".github/workflows/ryvn-lifecycle-hook-job-release.yaml"

jobs:
  release:
    uses: ryvn-technologies/ryvn-build-action/.github/workflows/release.yml@v2
    with:
      service_name: lifecycle-hook-job
    permissions:
      contents: write
      id-token: write
    secrets:
      RYVN_CLIENT_ID: ${{ secrets.RYVN_CLIENT_ID }}
      RYVN_CLIENT_SECRET: ${{ secrets.RYVN_CLIENT_SECRET }}
